"""Generate lib/sea/lanes.ts from lanes_data.py. Run validate_lanes.py first."""
import json
from lanes_data import NODES, EDGES, PORT_APPROACH
out = ["// AUTO-GENERATED by tools/lanes/gen_lanes_ts.py - do not edit by hand.",
       "// Hand-authored approximation of main commercial sea lanes, validated against",
       "// Natural Earth 50m land (0 land crossings). Not AIS-derived, not for navigation.",
       "export type LngLat = [number, number];",
       "export const LANE_NODES: Record<string, LngLat> = " + json.dumps(NODES, separators=(",", ":")) + ";",
       "export const LANE_EDGES: [string, string, string?][] = " + json.dumps([list(e) for e in EDGES], separators=(",", ":")) + ";",
       "export const PORT_APPROACH: Record<string, string> = " + json.dumps(PORT_APPROACH, separators=(",", ":")) + ";", ""]
open("../../lib/sea/lanes.ts", "w").write("\n".join(out))
print("wrote lib/sea/lanes.ts", len(NODES), "nodes", len(EDGES), "edges")
